SET @rownr=0;
insert into tr_header
(
	id,
	company_id,
	tr_id,
	tr_number,
	tr_number_old,
	tr_date,
	customer_id,
	customer_id_old,
	relation_customer_id,
	relation_description,
	customer_action_id,
	sumber_dana,
	tujuan_transaksi,
	description,
	numberofcopies,
	counter_id,
	cashier_id,
	status,
	created,
	updated,
	createdby,
	updatedby
)
select
	@rownr:=@rownr+1 AS id, 
  company_id,
	tr_id,
	tr_number,
	tr_number_old,
	tr_date,
	customer_id,
	customer_id_old,
	relation_customer_id,
	relation_description,
	customer_action_id,
	sumber_dana,
	tujuan_transaksi,
	description,
	numberofcopies,
	counter_id,
	cashier_id,
	status,
	created,
	updated,
	createdby,
	updatedby
	from ztrh
	order by tr_date,customer_id asc 